# .github/ISSUE_TEMPLATE/bug_report.yml
name: 🐞 Bug melden
description: Fehler oder unerwartetes Verhalten melden
title: "[Bug] "
labels: [bug]
body:
  - type: textarea
    id: beschreibung
    attributes:
      label: Was ist passiert?
      description: Beschreibe, was passiert ist und was du erwartet hättest.
      placeholder: Fehlerbeschreibung hier einfügen
    validations:
      required: true         # <-- neu: validations
  - type: textarea
    id: reproduktion
    attributes:
      label: Wie kann man das Problem nachstellen?
      placeholder: Schritte, Screenshots, Testdaten etc.
    validations:
      required: false
